### ISSUE TITLE
As of update to 2.0.9 sources a message is displayed that libhidapi is missing

### ISSUE THREAD

**Issue by fallahn** [fallahn/sdl2vs#2]
From a comment by brianJt on the [blog post](https://trederia.blogspot.com/2017/03/building-sdl2-for-android-with-visual.html)

"I have removed the use of that library from SDLActivity.java line 253 and the example runs. However it runs twice. From what I've read this may be the result of there being an AndroidManifest.xml also in the SD2 library build. Removing it from the ARM build made it run only once though not from the x86 build (possibly a manifest was still sticking around due to incremental builds)."

**Comment by gapkalov** [comment]
You can try this one
https://github.com/gapkalov/sdl2vs

**Comment by fallahn** [comment]
Fantastic, thank you!
