### ISSUE TITLE
How do I use libc++_shared.so?

### ISSUE THREAD

**Issue by Devacor** [fallahn/sdl2vs#5]
I can get this to build properly using libc++_static, but not libc++_shared, is it possible? What specific things do I need to do to get that to work?

**Comment by Devacor** [comment]
Aaaah, I had to choose it in the visual studio properties for each of my .so files "c++_shared" in "Use of STL" in the general section in the UI.

On top of this, I also manually had to specify the library in my  linker inputs. For my own code it looks like this:

c++_shared
c++abi
m
dl
GLESv1_CM
GLESv2
log
android
SDL2

For SDL2 it looks like that but without the "SDL2" entry.

Additionally I uncommented the line in Application.mk and put in:

APP_STL := c++_shared

That all seems to have it set up and running.

**Comment by fallahn** [comment]
Thanks for sharing the solution!
